### ISSUE TITLE
Missing menu bar when using self-compiled webinterface

### ISSUE THREAD

**Issue by verybadsoldier** [patrickjahns/esp_rgbww_webinterface#1]
The Wiki page describing the firmware build process (https://github.com/patrickjahns/esp_rgbww_firmware/wiki/1.1-Flashing) states that the webinterface files can be found in this file:
http://patrickjahns.github.io/esp_rgbww_firmware/release/esp_rgbww_firmware.zip

But it seems that the file "only" contains the binary spiffs but not the webinterce-tgzs.

So I compiled the webinterface myself which worked ok and I could build the firmware but then the menubar does not show up properly but looks like this:
![image](https://cloud.githubusercontent.com/assets/364469/24321842/a52b787a-1156-11e7-8d74-74298de02e82.png)

I tried to clear browser caches and it did not help. When flashing with the spiffs.bin from the prebuilt package then the website works as expected. Javascript console shows no errors.

I used Ubuntu 16.10 x64 and built the webinterface like this:
http://pastebin.com/GtqU6c8Z

This is how it looks when I build the firmware:
http://pastebin.com/pmQhdtn2

Any idea what went wrong? Or maybe there is somewhere a download link for pre-built webinterface files:

> app.min.css.gz
> app.min.js.gz
> index.html.gz
> init.html.gz

Thank you!

**Comment by patrickjahns** [comment]
You can find the latest webinterface here: 
https://github.com/patrickjahns/esp_rgbww_firmware/raw/gh-pages/release/esp_rgbww_webinterface.zip
